---
title: "Collections of Features"
description: | 
author:
  - name: Kris Sankaran
    affiliation: UW Madison
date: 2021-04-21
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
library("knitr")
opts_chunk$set(cache = FALSE, message = FALSE, warning = FALSE, echo = TRUE)
```

_[Reading](), [Recording](), [Rmarkdown]()_

1. The previous notes gave us a look into the features learned by a deep
learning model. However, we could only look at one feature (within one layer) at
a time. We also only studied an individual image. If we want to better
understand the representations learned by a network, we will need ways of
analyzing collections of features (taken from throughout the network), across
entire datasets.

2. This seems like an impossible task, but it turns out that, in real-world
models, the learned features tend to be highly correlated. Certain patterns of
activation tend to recur across similar images. This kind of structure makes it
possible to use clustering and dimensionality-reduction to begin to make sense
of the learned representations of individual networks.

3. Ideally, we could work with a matrix of samples by feature. The ij^{th}
element would be the activation of feature j on observation i.

4. This is unfortunately not immediately available — each feature map is
actually a small array, not a single number. There is no single way to aggregate
across the feature maps, and it is common to see people use the maximum,
average, norm, or variance of an individual feature map as a summary for how
strongly that feature activates on a given image. We will take the norm of
activations.

5. In the code block below, we loop over a random subsample of the cat vs. dog
training set, saving features from layers x and y.

6. Given this array, we can ask questions like, which neurons are most activated
for a particular image? or, which images induce the largest activations for a
particular neuron?

7. We can also consider all the images and neurons simultaneously. The code
below makes a heatmap of the activation matrix.

	A similar example is given in the reading, where coordinated views reveal that certain patterns of neuron activation encode the lifts of the pen or specific curve shapes in a handwriting generation network. 
	
8. We can also apply clustering and dimensionality reduction ideas to understand
the collection of activations. For example, below we run K-means on the
activation matrix. The 5 images closest to two different centroids are printed
below.

9. In general, we can treat the activations generated by a deep learning model
as themselves the object of data analysis. This can help us determine whether
the kinds of features that we want it to (high-level concepts, rather than just
colors or textures). It can also highlight instances where the model learns
features associated with concepts that we would rather it be invariant to (e.g.,
changes in season, variations in lighting).