---
title: "Spatial Data Formats"
description: |
  An overview of common formats, with illustrative examples.
author:
  - name: Kris Sankaran
    affiliation: UW Madison
date: 03-08-2021
output:
  distill::distill_article:
    self_contained: false
---

_[Reading](https://geocompr.robinlovelace.net/spatial-class.html), [Recording](), [Rmarkdown]()_

1. Spatial data come in two main formats: vector and raster. We’ll examine them
in detail in the next few lectures, but this lecture motivates the high-level
distinction and gives a few examples. It also shows how to read and write data
to and from these formats.

### Vector Data

2. Vector data formats are used to store geometric information, like the
locations of hospitals (points), trajectories of bus routes (lines), or
boundaries of counties (polygons). It’s useful to think of the associated data
as being spatially enriched data frames, with each row corresponding to one of
these geometric features.
	
3. Vector data are usually stored in `.geojson`, `.wkt`, `.shp`, or `.topojson`
formats. Standard data.frames cannot be used because then important spatial
metadata would be lost, like the Coordinate Reference System (to be explained in
the next lecture).

4. In R, these formats can be read using `read_sf` in the `sf` package. They can
be written using the `write_sf` function.

5. There is a surprising amount of public vector data available online. Using this [query^[It can be constructed easily using the wizard]](https://overpass-turbo.eu/s/14ma), I’ve downloaded locations of all hospital clinics in Madison.
	
Using this [query](https://overpass-turbo.eu/s/14m9), I’ve downloaded all the
bus routes.
	
	Here are the boundaries of the [lakes](https://overpass-turbo.eu/s/14mb).
	
	Many organizations prepare geojson data themselves and make it publicly available; e.g., the boundaries of rivers or glaciers. Don’t worry about how to visualize these data at this point — I just want to give some motivating examples.

### Raster Data

6. Raster data give a measurement along a spatial grid. You can think of them as
spatially enriched matrices, where the metadata says where on the earth each
entry of the matrix is associated with.

7. Raster data are often stored in `tiff` format. They can be read in using the
`brick` function in the `raster` library, and can be written using
`writeRaster`.

8. Some of the most common types of public raster data are satellite images or
derived measurements, like elevation maps. For example, the code below shows an
image of a neighborhood in Paris.
	
Here are is data on elevation in Zion national park.


### Installation

9. A note about R packages: for historical reasons, spatial data libraries in R
reference a few command line programs, like `gdal` and `proj`. Since these
command line programs are not themselves a part of R, they need to be installed
before the corresponding R packages. The process will differ from operating
system to operating system, and the experience can be frustrating, especially
when the R packages don’t recognize the underlying system installation. I
recommend following the instructions on [this
page](https://github.com/r-spatial/sf) and reaching out early if you have any
issues.
