---
title: "Spatial Data Interaction"
description: |
  Some strategies for interactively visualizing spatial data.
author:
  - name: Kris Sankaran
    affiliation: UW Madison
date: 03-12-2021
output:
  distill::distill_article:
    self_contained: false
---

_[Reading](https://geocompr.robinlovelace.net/spatial-class.html), [Recording](), [Rmarkdown]()_

1. These are optional notes. The reading does not cover interactivity in spatial
data contexts, and there will be no problems in this class related to
interactive spatial data visualization. However, these notes may be useful if
you ever work on a spatial data project with interactive components.

2. In `vega-lite`, vector data can be visualized using `vl.markGeoshape`. Any
fields contained within the vector dataset can be visually encoded in the marks.
This is analogous to `geom_sf` in ggplot2.

3. Spatial data are often amenable to dynamic linking. Selections on the map can
highlight elements in a complementary figure. For example, hovering over
geographic elements might highlight series in a time series plot or update a
barchart placed on the side. This is an example with random histogram data.

4. Alternatively, selections in a complementary figure can highlight the
associated geographic elements.

5. The example below reproduces the population growth figure from (UIC Bremer)
using vega-lite. Another classic example of linked spatial data visualization is
the DC HomeSearcher.

6. Sometimes it’s useful to add an interactive map background to a vector
dataset. In this case, the `leaflet` package in R can be useful. By fetching
background images on which vector data can be plotted, it is like `ggmap`.
Unlike `ggmap`, the backgrounds can be panned and zoomed.