---
title: "STAT 479: HW4"
author: Spring 2026
format: pdf
execute:
    echo: true
    message: false
    warning: false
    cache: false
---

## Submission Details

Upload your solution to Gradescope as a PDF document. Include all relevant
figures within your explanations. Include all relevant code. You may use either
R or python.

## Evaluation Criteria

**Technical Precision**

  - All quantities defined correctly.
  - Claims are made precisely, no vagueness.
  - Figures have labeled axes, legends, and descriptive captions.

**Completeness**:

  - Each method choice is justified, not just described.
  - Claims are grounded in readings, lectures, or original code.
  - Logical connections between claims and evidence.
  - Caveats are acknowledged where relevant.

**Clarity**

  - Appropriate formatting and demarcation into sections.
  - Grammatically correct prose (not sentence fragments).
  - Visualizations referenced in prose, not simply included without comment.
  - No wordiness.

**Code quality**

  - Only necessary outputs are shown, and manageable code size.
  - Code is logically organized into functions or split into clearly commented sections.
  - No unnecessary code or duplication.
  - Logical variables names.

## Description

This problem gives you a chance to apply post-hoc interpretability techniques
(global variable importance, CP profiles, and SHAP) to a problem of your choice.
It highlights potential mistakes in implementation and interpretation that
sometimes appear in practice and suggests best practices to decrease the risk.
Write this as if it were a report for colleagues after graduation -- strong
reports should stand alone as in your personal project portfolio.

Potential data sources: TidyTuesdays, Data is Plural, HuggingFace, Kaggle
Datasets, Google Dataset Search, AWS Data Registry, Wisconsin DNR, IPUMS Census
Data, 538, Data.gov, Madison Open Data, Bioconductor Datasets, Awesome Public
Data.

a. **Problem Formulation**. Describe your dataset and problem context.

    (i) What is the real world problem and how can it be framed as a prediction task?
    (ii) Who benefits from the explanation and what choices does it guide?
    (iii) How did you access the data and what preliminary data processing (if any) did you apply? E.g., did you do anything special to handle ID variables, missing values, free text fields? Did you create any new features (e.g., day-of-week from date)?

b. **Model Training**. Train a model that is not intrinsically interpretable,
like tree ensembles or deep learning (for other choices, please contact
instructors).

    (i) How did you tune model hyperparameters? If using cross-validation, ensure there is no data leakage (e.g., the same person should not appear in both in training and test folds).
    (ii)  What is the out-of-sample prediction accuracy?

c. **Explanation 1.** Apply one of the following methods: CP profiles, model-based SHAP, or model-agnostic SHAP.

    (i) Does your method support local explanations, global explanations or both?
    (ii) On what scale is the explanation output? For classification, distinguish between attributions on probability vs. log-odds scales.
    (iii) Create substantive visualizations based on your explanation, and summarize their main takeaways. For example, if your method supports local explanations, do not simply show population level summaries. If explaining a few selected samples, explain why you selected them (e.g., they are representative or are instructive failure modes).
    (iv) What is one way your output could be misread, and how would you correct it?

d. **Explanation 2.** Repeat part (c) for one other method. If you chose a
model-agnostic SHAP method, you may choose a different model-agnostic SHAP
method here.

e. **Method Description** Describe one of your two methods as if it were for a company/lab-wide report. What is one strength and one limitation? Your explanation should be accessible without an extensive background in statistics.

f. **Checks**.

    (i) Check the correlation structure of your predictors. How do the results how you interpret any of your outputs? Do your selected methods risk extrapolation? Do they risk assigning nonzero attributions to irrelevant features?
    (ii) Does your explanation method have any hyperparameters? What do those hyperparameters control? Test the sensitivity of one of your outputs to a change in one of your hyperparameters.
    (iii) How do the outputs from the two explanation methods compare and contrast?