
### 2. Definitions

* global vs. local interpretability

* intrinsic vs. post-hoc

* workflow

---

### Global interpretability

---

### Future examples

---

### Local interpretability

---

### Future examples

---

## Intrinsic Interpretability vs. Post-hoc Explanations

- Intrinsically interpretable: Build a "glass box" from the start. Sparsity and simulatability ensure the model is inherently readable.

- Post Hoc: Inspect an already trained "black box" model, which can be chosen simply to maximize accuracy without regard to interpretability.

---

### Intrinsic interpretability

---

### Sparsity

---

### Simulatability

---

### Modularity

---

### Exercise: Linear models

---

### Post-hoc interpretability

---

### Feature importance

---

### Additional context

---

### Interpretability-accuracy trade-offs

- For many datasets, simple models (like decision trees) offer high descriptive
accuracy but are not as accurate as more complex models.

- Similarly, deep neural networks might predict the future well but not be
amenable to accurate descriptions.

---

### Does it exist?

---

### Exercise: Local feature importance

---

### Recommended workflow

(why we should care)

---

### Design

---

### Internal accuracy

---

### Stability

---

### Internal interpretability

---

### Compare interpretations

---

### External checks

---

### Working with non-statisticians

---