
### 15. Introduction to Respresentation Learning

* motivating case study

* deep representations

* pytorch package

---

### Learning outcomes

* Analyze large-scale foundation models using methods like sparse autoencoders and describe their relevance to problems of model control and AI-driven design.
* Within a specific application context, evaluate the trade-offs associated with competing interpretable machine learning techniques.

---

### Shrimp aquaculture

---

### Ecological importance

---

### Aerial imagery

---

### Value of ML

---

### Relevant features

---

## Deep Representations

---

### Motivation

---

### Handcrafted vs. automatic features

---

### Image representations

---

### Text representations

---

### Multilayer models

---

### Mixing regressors

---

### Exercise: Mixing classifiers

---

### Training

---

### Example losses

---

### Example layers

---

### Architerctures

---

## Pytorch

---

### Autograd

---

### Data loaders

---

### `nn.Module`

---

### Loss + Optimizers

---

### Training

---

### Parameters

---

### Predictions

---

### Exercise: Two moons classification