---
title: ""
description: |

author:
  - name: Kris Sankaran
    affiliation: UW Madison
date: 
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, message = FALSE, warning = FALSE, echo = TRUE)
library("robservable")
```

_[Reading](), [Recording](), [Rmarkdown]()_

1. The goal of clustering is to discover distinct groups within a dataset. In an
ideal clustering, samples are very different between groups, but relatively
similar within groups. At the end of a standard (non-hierarchical) clustering
routine, $K$ clusters have been identified, and each sample is assigned to one
of these $K$ clusters. The number of clusters $K$ must be chosen by the user.

2. Clustering gives a compressed representation of the dataset. Therefore,
clustering is useful for getting a quick overview of the coarse structure in a
dataset.

3. For example, clustering can be used in the following applications,

	* User segmentation: A marketing study might try to summarize different user
	behaviors by clustering into a few key « segments. » Each segment might
	motivate a different type of marketing campaign.
	* Gene expression profiling: A genomics study might try to identify genes whose
	expression levels are similar across different experimental conditions. These
	gene clusters might be responsible for a shared biological function.
	
4. K-means is a particular algorithm for finding clusters. First, it randomly
initializes $K$ cluster centers. Then, it alternates the following two steps
until convergence,

	* Assign points to their nearest cluster center.
	* Update the $K$ centers to be the averages of points within their cluster.
	
Since we have to take an average for each coordinate, we require that our data
be quantitative, not categorical^[To work with data of different types, it's
possible to use a variant called $K$-medoids, but this is beyond the scope of
this class.].
	
5. There are two pieces of derived data that are generated by this routine,

  * The cluster assignments. Each observation is assigned to one of the $K$
  clusters.
	* The cluster centers. We expect observations within each cluster to look
	similar to its cluster center.
	
6. The figure below visualizes the cluster centers in relation to the original
source data.

7. It’s often of interest to relate the cluster assignments to complementary
data, to see whether the clustering reflects any previously known differences
between the observations, which weren’t directly used in the clustering
algorithm.

8. Be cautious: Outliers, nonspherical shapes, and variations in density will
mess you up, if you just use $K$-means.

9. The goals of clustering are highly problem dependent, and different goals
might call for alternative algorithms. For example, consider the ways clustering
might be used to understand disease transmission. One problem might be to
cluster the DNA sequences of the pathogenic agent, to recover its evolutionary
history. This could be done using hierarchical clustering (next lecture). A
second problem might be to determine whether patient outcomes might be driven by
one of a few environmental factors, in which case a $K$-means clustering would
be reasonable. A third use would be to perform contact tracing, based on a
network clustering algorithm (related to the networks lectures, but beyond the
scope of this class).
