---
title: "Uniform Manifold Approximation and Projection"
description: |
    An overview of the UMAP algorithm.
author:
  - name: Kris Sankaran
    affiliation: UW Madison
date: 2021-4-01
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
library("knitr")
opts_chunk$set(cache = FALSE, message = FALSE, warning = FALSE, echo = TRUE)
```

_[Reading](),[Recording](),[Rmarkdown]()_

1. Nonlinearity can give a more faithful representation of the data when the
data don’t lie on a low-dimensional linear subspace.

2. For example, suppose the data were shaped like this. There is no
one-dimensional line through these data that separate the groups well. We will
need an alternative approach to reducing dimensionality if we want to preserve
nonlinear structure.

3. From a high-level, the intuition behind UMAP is to (a) build a graph joining
nearby neighbors in the original high-dimensional space, and then (b) layout the
graph in a lower-dimensional space.

4. For example, consider the 2-dimensional sine wave below. If we build a graph,
we can try to layout the resulting nodes and edges on a 1-dimensional line in a
way that approximately preserves the ordering.

5. A natural way to build a graph is to join each node to it’s $K$ closest
neighbors. The choice of $K$ will influence the final reduction, and it is
treated as a hyperparameter of UMAP.

6. Larger values of $K$ prioritize preservation of global structure, while
smaller $K$ will better reflect local differences. This property is not
obvious a priori, but is suggested by the type of toy simulations described in
the reading.

7. One detail in the graph construction: In UMAP, the edges are assigned weights
depending on how close the neighbors they link are, relative to the distance to
the closest neighbor. This is what the authors mean by a « fuzzy » nearest
neighbor graph. The fuzziness allows the algorithm to distinguish neighbors that
are very close from those that are far, even though they all lie within a
$K$-nearest-neighborhood.

8. Once the graph is constructed, there is another question of how the graph
layout should proceed. UMAP uses a variant of force-directed layout, and the
strengths of the springs is another hyperparameter. Lower tension on the springs
allow the points to spread out more losely, higher tension forces points closer
together. This is a second hyperparameter of UMAP.

9. These two hyperparameters — the number of nearest neighbors $K$ and the
layout tension — are the only two hyperparameters of $U$-map.

10. Examples of what it does to a few different toy datasets.

11. In R, we can implement this using almost the same code as we used for PCA.

12. UMAP returns a low-dimensional atlas relating the points, but it does not
provide any notion of derived features.

13. We can summarize the properties of UMAP,

  * **Global or local structure**: The number of nearest neighbors $K$ used
  during graph construction can be used modulate the emphasis of global vs.
  local structure.
  * **Nonlinear**: UMAP can reflect nonlinear structure in high-dimensions.
  * **No interpretable features**: UMAP only returns the map between points, and
  there is no analog of components to describe how the original features were
  used to construct the map.
  * **Slower**: While UMAP is much faster than comparable nonlinear
  dimensionality reduction algorithms, it is still slower than linear
  approaches.
  * **Nondeterministic**: The output from UMAP can change from run to run, due
  to randomness in the graph layout step. If exact reproducibility is required,
  a random seed should be set.
